=== GitHubsteven/building-block/building-xml/src/main/dtd/note.dtd
<!ELEMENT note (title+,to,from,heading,body,(name|username),square,contact,payment,author)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT to (#PCDATA)>
        <!ELEMENT from (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT body (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT username (#PCDATA)>
        <!ELEMENT square (#PCDATA)>
        <!ELEMENT contact (#PCDATA)>
        <!ELEMENT payment (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ATTLIST square width CDATA #REQUIRED>
        <!ATTLIST contact fax CDATA #IMPLIED>
        <!ATTLIST payment type (check|cash) "cash">
        <!ENTITY writer "Donald Duck.">
        <!ENTITY copyright "Copyright runoob.com">

=== GitHubsteven/building-block/building-xml/src/main/xml/note.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "note.dtd">

<note>
    <title>title</title>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
    <name>name</name>
    <square width="12">2</square>
    <contact>163-234</contact>
    <payment type="check"/>
    <author>author</author>
</note>
